from .nemotron import NemotronGenerator
from .prompts import (
    DEFAULT_MACRO_TOPICS_PROMPT_TEMPLATE,
    DEFAULT_OPEN_QA_FROM_TOPICS_PROMPT_TEMPLATE,
    DEFAULT_SUBTOPICS_PROMPT_TEMPLATE,
)

__all__ = [
    "NemotronGenerator",
    "DEFAULT_MACRO_TOPICS_PROMPT_TEMPLATE",
    "DEFAULT_SUBTOPICS_PROMPT_TEMPLATE",
    "DEFAULT_OPEN_QA_FROM_TOPICS_PROMPT_TEMPLATE",
]
